/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import utils.Funtions;
import utils.Inlet;

/**
 *
 * @author Roger - Rp
 * @author Daniela - danielam
 * 
 */
public class MenuOperacionGUI extends javax.swing.JFrame {

    /**
     * Creates new form OperacionGUI
     */
    public MenuOperacionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_or = new javax.swing.JButton();
        btn_and = new javax.swing.JButton();
        btn_not = new javax.swing.JButton();
        btn_xor = new javax.swing.JButton();
        btn_diferencia = new javax.swing.JButton();
        btn_potencia = new javax.swing.JButton();
        atras = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conjuntos");

        btn_or.setText("Unión");
        btn_or.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_orMouseClicked(evt);
            }
        });
        btn_or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_orActionPerformed(evt);
            }
        });

        btn_and.setText("Intersección");
        btn_and.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_andMouseClicked(evt);
            }
        });
        btn_and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_andActionPerformed(evt);
            }
        });

        btn_not.setText("Complemento");
        btn_not.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_notMouseClicked(evt);
            }
        });
        btn_not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notActionPerformed(evt);
            }
        });

        btn_xor.setText("Diferencia Simetrica");
        btn_xor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xorMouseClicked(evt);
            }
        });
        btn_xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xorActionPerformed(evt);
            }
        });

        btn_diferencia.setText("Diferencia");
        btn_diferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_diferenciaMouseClicked(evt);
            }
        });
        btn_diferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diferenciaActionPerformed(evt);
            }
        });

        btn_potencia.setText("Potencia");
        btn_potencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_potenciaMouseClicked(evt);
            }
        });
        btn_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potenciaActionPerformed(evt);
            }
        });

        atras.setText("Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_or, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_and, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_not, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_diferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_potencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(atras)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_or)
                .addGap(18, 18, 18)
                .addComponent(btn_and)
                .addGap(18, 18, 18)
                .addComponent(btn_not)
                .addGap(18, 18, 18)
                .addComponent(btn_xor)
                .addGap(18, 18, 18)
                .addComponent(btn_diferencia)
                .addGap(18, 18, 18)
                .addComponent(btn_potencia)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_orActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación OR", Inlet.OR);
        op.setVisible(true);
        
    }//GEN-LAST:event_btn_orActionPerformed

    private void btn_orMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_orMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_orMouseClicked

    private void btn_andMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_andMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_andMouseClicked

    private void btn_notMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_notMouseClicked

    private void btn_xorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xorMouseClicked

    private void btn_diferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_diferenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_diferenciaMouseClicked

    private void btn_potenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_potenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_potenciaMouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        //reiniciar
        setVisible(false);
        //dispose();   
        OperacionGUI op = new OperacionGUI();
        op = null;       
        Funtions.initialize(Inlet.CONJUNTO_A);
        Funtions.initialize(Inlet.CONJUNTO_B);
        Funtions.initialize(Inlet.UNIVERSAL);
        Funtions.initialize(Inlet.AUX_CONJUNTO_A);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_atrasMouseClicked

    private void btn_andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_andActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación AND", Inlet.AND);//llamar a la ventanas para mostrar las operaciones siguiendo un numero
        op.setVisible(true);
    }//GEN-LAST:event_btn_andActionPerformed

    private void btn_notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación NOT", Inlet.NOT);
        op.setVisible(true);
    }//GEN-LAST:event_btn_notActionPerformed

    private void btn_xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xorActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación XOR", Inlet.XOR);
        op.setVisible(true);
    }//GEN-LAST:event_btn_xorActionPerformed

    private void btn_diferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diferenciaActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación Diferencia", Inlet.DIFERENCIA);
        op.setVisible(true);
    }//GEN-LAST:event_btn_diferenciaActionPerformed

    private void btn_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potenciaActionPerformed
        // TODO add your handling code here:
        OperacionGUI op = new OperacionGUI("Operación Potencia", Inlet.POTENCIA);
        op.setVisible(true);
    }//GEN-LAST:event_btn_potenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOperacionGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton btn_and;
    private javax.swing.JButton btn_diferencia;
    private javax.swing.JButton btn_not;
    private javax.swing.JButton btn_or;
    private javax.swing.JButton btn_potencia;
    private javax.swing.JButton btn_xor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
